--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: albuns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.albuns (
    id bigint NOT NULL,
    author character varying(80),
    description character varying(500),
    foto character varying(255),
    kind character varying(80),
    name character varying(225) NOT NULL,
    rate integer,
    release character varying(80)
);


ALTER TABLE public.albuns OWNER TO postgres;

--
-- Name: albuns_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.albuns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.albuns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: albuns albuns_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.albuns
    ADD CONSTRAINT albuns_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

